.TH SysMonitor 7 18/4/2023

.SH Name

SysMonitor - A C program to manage processes

.SH Description

The SysMonitor program allows the user to
.B 
list
system process and user processes 
.I
(In both a normal way and an interactive way)
,
.B
run 
a process/program,
.B
stop 
a specific process or all the processes associated under 1 name,
.B
send signals 
to a specific program.

.SH License
A
.B
MIT License
is assigned to the task's Github page.
